//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharpfirstpass
{
	public static class Vector3Extensions
	{
		public static Vector3 Round(this Vector3 v, float interval)
		{
			v.x = Mathf.Round(v.x / interval) * interval;
			v.y = Mathf.Round(v.y / interval) * interval;
			v.z = Mathf.Round(v.z / interval) * interval;

			return v;
		}
	}
}

